[2025-02-05T20:47:14.578+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-05T20:47:14.587+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_que_faire_a_paris.transform_data manual__2025-02-05T20:47:11.145227+00:00 [queued]>
[2025-02-05T20:47:14.592+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_que_faire_a_paris.transform_data manual__2025-02-05T20:47:11.145227+00:00 [queued]>
[2025-02-05T20:47:14.593+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-05T20:47:14.601+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform_data> on 2025-02-05 20:47:11.145227+00:00
[2025-02-05T20:47:14.605+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2825) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-05T20:47:14.606+0000] {standard_task_runner.py:72} INFO - Started process 2827 to run task
[2025-02-05T20:47:14.606+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_que_faire_a_paris', 'transform_data', 'manual__2025-02-05T20:47:11.145227+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/dag_que_faire_a_paris.py', '--cfg-path', '/tmp/tmpfgabtozv']
[2025-02-05T20:47:14.608+0000] {standard_task_runner.py:105} INFO - Job 94: Subtask transform_data
[2025-02-05T20:47:14.642+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_que_faire_a_paris.transform_data manual__2025-02-05T20:47:11.145227+00:00 [running]> on host b176106a6d6f
[2025-02-05T20:47:14.809+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_que_faire_a_paris' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T20:47:11.145227+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T20:47:11.145227+00:00'
[2025-02-05T20:47:14.810+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-05T20:47:15.096+0000] {dag_que_faire_a_paris.py:167} INFO - âœ… Transformation completed successfully!
[2025-02-05T20:47:15.102+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-05T20:47:15.110+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-05T20:47:15.114+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_que_faire_a_paris, task_id=transform_data, run_id=manual__2025-02-05T20:47:11.145227+00:00, execution_date=20250205T204711, start_date=20250205T204714, end_date=20250205T204715
[2025-02-05T20:47:15.142+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-05T20:47:15.154+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-05T20:47:15.158+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
