[2025-02-04T21:21:07.024+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-04T21:21:07.033+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_que_faire_a_paris.extract_data manual__2025-02-04T21:21:05.961713+00:00 [queued]>
[2025-02-04T21:21:07.038+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_que_faire_a_paris.extract_data manual__2025-02-04T21:21:05.961713+00:00 [queued]>
[2025-02-04T21:21:07.040+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-04T21:21:07.050+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_data> on 2025-02-04 21:21:05.961713+00:00
[2025-02-04T21:21:07.068+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=130) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-04T21:21:07.069+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_que_faire_a_paris', 'extract_data', 'manual__2025-02-04T21:21:05.961713+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/dag_que_faire_a_paris.py', '--cfg-path', '/tmp/tmp7wva2d1q']
[2025-02-04T21:21:07.084+0000] {standard_task_runner.py:72} INFO - Started process 132 to run task
[2025-02-04T21:21:07.086+0000] {standard_task_runner.py:105} INFO - Job 42: Subtask extract_data
[2025-02-04T21:21:07.146+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_que_faire_a_paris.extract_data manual__2025-02-04T21:21:05.961713+00:00 [running]> on host ed2435b8d4d0
[2025-02-04T21:21:07.317+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_que_faire_a_paris' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-04T21:21:05.961713+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-04T21:21:05.961713+00:00'
[2025-02-04T21:21:07.331+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-04T21:21:09.193+0000] {dag_que_faire_a_paris.py:36} INFO - Extraction completed successfully!
[2025-02-04T21:21:09.195+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-04T21:21:09.201+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-04T21:21:09.202+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_que_faire_a_paris, task_id=extract_data, run_id=manual__2025-02-04T21:21:05.961713+00:00, execution_date=20250204T212105, start_date=20250204T212107, end_date=20250204T212109
[2025-02-04T21:21:09.235+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-04T21:21:09.248+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-04T21:21:09.253+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
