[2025-02-06T15:41:02.985+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-06T15:41:02.995+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_que_faire_a_paris.transform_data manual__2025-02-06T15:41:00.352353+00:00 [queued]>
[2025-02-06T15:41:03.002+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_que_faire_a_paris.transform_data manual__2025-02-06T15:41:00.352353+00:00 [queued]>
[2025-02-06T15:41:03.010+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-06T15:41:03.023+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform_data> on 2025-02-06 15:41:00.352353+00:00
[2025-02-06T15:41:03.028+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=8124) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-06T15:41:03.029+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_que_faire_a_paris', 'transform_data', 'manual__2025-02-06T15:41:00.352353+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/dag_que_faire_a_paris.py', '--cfg-path', '/tmp/tmp6z8ohjv8']
[2025-02-06T15:41:03.034+0000] {standard_task_runner.py:72} INFO - Started process 8126 to run task
[2025-02-06T15:41:03.035+0000] {standard_task_runner.py:105} INFO - Job 115: Subtask transform_data
[2025-02-06T15:41:03.094+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_que_faire_a_paris.transform_data manual__2025-02-06T15:41:00.352353+00:00 [running]> on host b176106a6d6f
[2025-02-06T15:41:03.265+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_que_faire_a_paris' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-06T15:41:00.352353+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-06T15:41:00.352353+00:00'
[2025-02-06T15:41:03.266+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-06T15:41:03.523+0000] {dag_que_faire_a_paris.py:172} INFO - âœ… Transformation completed successfully!
[2025-02-06T15:41:03.525+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-06T15:41:03.532+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-06T15:41:03.533+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_que_faire_a_paris, task_id=transform_data, run_id=manual__2025-02-06T15:41:00.352353+00:00, execution_date=20250206T154100, start_date=20250206T154102, end_date=20250206T154103
[2025-02-06T15:41:03.576+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-06T15:41:03.592+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-06T15:41:03.595+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
