[2025-02-05T16:29:21.834+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-05T16:29:21.848+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_que_faire_a_paris.extract_data manual__2025-02-05T16:29:20.399386+00:00 [queued]>
[2025-02-05T16:29:21.855+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_que_faire_a_paris.extract_data manual__2025-02-05T16:29:20.399386+00:00 [queued]>
[2025-02-05T16:29:21.855+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-05T16:29:21.866+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_data> on 2025-02-05 16:29:20.399386+00:00
[2025-02-05T16:29:21.871+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1691) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-05T16:29:21.872+0000] {standard_task_runner.py:72} INFO - Started process 1693 to run task
[2025-02-05T16:29:21.872+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_que_faire_a_paris', 'extract_data', 'manual__2025-02-05T16:29:20.399386+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/dag_que_faire_a_paris.py', '--cfg-path', '/tmp/tmpnq91uxz3']
[2025-02-05T16:29:21.877+0000] {standard_task_runner.py:105} INFO - Job 82: Subtask extract_data
[2025-02-05T16:29:21.946+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_que_faire_a_paris.extract_data manual__2025-02-05T16:29:20.399386+00:00 [running]> on host b176106a6d6f
[2025-02-05T16:29:22.324+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_que_faire_a_paris' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T16:29:20.399386+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T16:29:20.399386+00:00'
[2025-02-05T16:29:22.325+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-05T16:29:24.958+0000] {dag_que_faire_a_paris.py:40} INFO - âœ… Extraction completed successfully!
[2025-02-05T16:29:24.964+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-05T16:29:24.972+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-05T16:29:24.973+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_que_faire_a_paris, task_id=extract_data, run_id=manual__2025-02-05T16:29:20.399386+00:00, execution_date=20250205T162920, start_date=20250205T162921, end_date=20250205T162924
[2025-02-05T16:29:25.023+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-05T16:29:25.049+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-05T16:29:25.056+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
