[2025-02-05T20:38:52.314+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-05T20:38:52.324+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_que_faire_a_paris.transform_data manual__2025-02-05T20:38:49.266465+00:00 [queued]>
[2025-02-05T20:38:52.330+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_que_faire_a_paris.transform_data manual__2025-02-05T20:38:49.266465+00:00 [queued]>
[2025-02-05T20:38:52.330+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-05T20:38:52.340+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform_data> on 2025-02-05 20:38:49.266465+00:00
[2025-02-05T20:38:52.345+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2709) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-05T20:38:52.346+0000] {standard_task_runner.py:72} INFO - Started process 2711 to run task
[2025-02-05T20:38:52.347+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_que_faire_a_paris', 'transform_data', 'manual__2025-02-05T20:38:49.266465+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/dag_que_faire_a_paris.py', '--cfg-path', '/tmp/tmp3bobd6qr']
[2025-02-05T20:38:52.349+0000] {standard_task_runner.py:105} INFO - Job 91: Subtask transform_data
[2025-02-05T20:38:52.380+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_que_faire_a_paris.transform_data manual__2025-02-05T20:38:49.266465+00:00 [running]> on host b176106a6d6f
[2025-02-05T20:38:52.548+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_que_faire_a_paris' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T20:38:49.266465+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T20:38:49.266465+00:00'
[2025-02-05T20:38:52.549+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-05T20:38:52.787+0000] {dag_que_faire_a_paris.py:152} INFO - âœ… Transformation completed successfully!
[2025-02-05T20:38:52.788+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-05T20:38:52.794+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-05T20:38:52.794+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_que_faire_a_paris, task_id=transform_data, run_id=manual__2025-02-05T20:38:49.266465+00:00, execution_date=20250205T203849, start_date=20250205T203852, end_date=20250205T203852
[2025-02-05T20:38:52.841+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-05T20:38:52.853+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-05T20:38:52.856+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
