[2025-02-04T21:44:24.796+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-04T21:44:24.805+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_que_faire_a_paris.extract_data manual__2025-02-04T21:44:24.303987+00:00 [queued]>
[2025-02-04T21:44:24.810+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_que_faire_a_paris.extract_data manual__2025-02-04T21:44:24.303987+00:00 [queued]>
[2025-02-04T21:44:24.810+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-04T21:44:24.818+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_data> on 2025-02-04 21:44:24.303987+00:00
[2025-02-04T21:44:24.822+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=131) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-04T21:44:24.824+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_que_faire_a_paris', 'extract_data', 'manual__2025-02-04T21:44:24.303987+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/dag_que_faire_a_paris.py', '--cfg-path', '/tmp/tmp272e1fxt']
[2025-02-04T21:44:24.850+0000] {standard_task_runner.py:72} INFO - Started process 133 to run task
[2025-02-04T21:44:24.851+0000] {standard_task_runner.py:105} INFO - Job 52: Subtask extract_data
[2025-02-04T21:44:24.904+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_que_faire_a_paris.extract_data manual__2025-02-04T21:44:24.303987+00:00 [running]> on host 2023d4c64a22
[2025-02-04T21:44:25.066+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_que_faire_a_paris' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-04T21:44:24.303987+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-04T21:44:24.303987+00:00'
[2025-02-04T21:44:25.068+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-04T21:44:25.561+0000] {dag_que_faire_a_paris.py:34} INFO - Extraction completed successfully!
[2025-02-04T21:44:25.563+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-04T21:44:25.569+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-04T21:44:25.570+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_que_faire_a_paris, task_id=extract_data, run_id=manual__2025-02-04T21:44:24.303987+00:00, execution_date=20250204T214424, start_date=20250204T214424, end_date=20250204T214425
[2025-02-04T21:44:25.589+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-04T21:44:25.603+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-04T21:44:25.608+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
